# Generated by Django 2.1.5 on 2019-01-19 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Linux_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_distribution_pretty_name', models.CharField(max_length=6)),
                ('machine_kernel_version', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Log_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=80)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=15)),
                ('machine_name', models.CharField(max_length=20)),
                ('machine_os_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Linux_details')),
            ],
        ),
        migrations.AddField(
            model_name='log_template',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Machine_details'),
        ),
        migrations.AddField(
            model_name='log_template',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='linux_details',
            unique_together={('machine_distribution_pretty_name', 'machine_kernel_version')},
        ),
    ]
