# Generated by Django 2.1.5 on 2019-01-19 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial_Error_keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('Problem', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Serial_log_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('err_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriallog.Serial_Error_keywords')),
                ('log_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Log_template')),
            ],
        ),
    ]
